.gitignore, flake.lock, flake.nix, wiki/mantenimiento/Metodologia_de_desarrollo.md
[Link al issue en ClickUp]()
Se añadieron los hooks de pre-commit para forzar la calidad de los commits
=> feat: Added precommit hooks to nix devenv

.github/workflows/main.yml
Esta PR agrrega una github action que verifica que las PRs sigan el formato correcto de conventional commits. La configuración se creó [en base a la documentación](https://github.com/amannn/action-semantic-pull-request)
Database: PRs …
=> feat(CI/CD): Convetional Commits github action

wiki/mantenimiento/Metodologia_de_desarrollo.md
Se mejoró la descripción de conventional commits y se agregó una sección que describe quién es el responsable final de mergear una PR …
=> feat: description to conventional commit tags

.github/workflows/main.yml, wiki/mantenimiento/Guia_de_contribución.md, wiki/mantenimiento/Metodologia_de_desarrollo.md
Se añadió una guía de contribución a la wiki, para facilitar la creación de las PRs.
Nix: PRs que modifican el entorno de desarrollo en …
=> feat: added contribution guide

wiki/mantenimiento/Metodologia_de_desarrollo.md
Se creó la sección de CI/CD y se agregaron sus contribuidores
CI/CD: PRs …
=> feat: added CI/CD section and contributors.

wiki/mantenimiento/Metodologia_de_desarrollo.md
=> feat: user added to nix

wiki/mantenimiento/README.md, wiki/mantenimiento/db/README.md
Se añadió una introducción al diagrama ER dentro de la base de datos, también se mejoraron los estilos de los MD según las indicaciones de los hooks de precommit
Wiki: …
=> feat: Added ER diagram and intro to it.

flake.nix
Se actualizaron la lista de los reviewers para el backend …
=> fix: Postgres host

wiki/mantenimiento/db/README.md
[Link al issue en ClickUp](https://app.clickup.com/t/86azyk9wm)
Se aplicó la 4NF a la tabla de privilegio usuario.
CI/CD: PRs …
=> fix: 4NF applied to privilegio usuario

wiki/mantenimiento/db/README.md
[Link al issue en ClickUp](https://app.clickup.com/t/86azyk9wm)
Se cambió el tipo de dato de la variable privilegio-usuario en la tabla privilegio-usuario …
=> fix: data type correction in table privilegio-usuario

wiki/mantenimiento/Metodologia_de_desarrollo.md
Se añadieron usuarios a trabajar en Database y en wiki …
=> feat: added users to db and wiki

database/init.sql
[Link al issue en ClickUp](https://app.clickup.com/t/86azn0q3n)
Implementación del diagrama ER en PostgreSQL.
CI/CD: PRs …
=> feat: Implemented PostgreSQL tables into init.sql from ER Diagram

wiki/mantenimiento/db/README.md
[Link al issue en ClickUp](https://app.clickup.com/t/86azyk9wm)
Se normalizó la entidad de paciente a 4NF …
=> fix: normalized paciente entity to 4NF

database/tables.sql
Se actualizaron la lista de los reviewers para el backend …
=> fix: tables accidental rollback and order

database/inserts.sql, flake.nix
Se actualizaron la lista de los reviewers para el backend …
=> feat: inserts added for Database, usuario-antecedente_paciente

wiki/mantenimiento/Metodologia_de_desarrollo.md
[Link al issue en ClickUp]()
Se aclaró un poco mejor la sección de metodología de desarrollo y también se agregó la rama de staging, usada principalmente para CI/CD y autopublicación en un ambiente de testing.
Wiki: …
=> docs: improved methodology section

dprint.json, sanitas_frontend/.eslintrc.cjs, sanitas_frontend/package.json, sanitas_frontend/src/App.jsx, sanitas_frontend/src/main.jsx, sanitas_frontend/vite.config.js
[Link al issue en Notion](https://www.notion.so/Setup-Formatter-c70d5d3c189f4cb29b1c7caca5e97a74?pvs=4)
Se actualizaron la lista de los reviewers para el backend
Nix: PRs que modifican …
=> feat: dprint formatter added

pull_request_template.md
Se actualizó la template para las PRs del proyecto.
=> fix: PR template

.github/workflows/PRs.yml, .github/workflows/frontend.yml
Añadi los workflos a .github que se ejecutaran al hacer pr 
Database: PRs que modifican lógica …
=> feat: workflows added to .github for Frontend

.github/workflows/deploy.yml
Workflow para hacer deploy sobre los push en la rama staging
- \[ ] Asegurate que la PR pase todos los chequeos de CI.
Database: PRs que modifican lógica …
=> feat: Deploy frontend workflow

.github/workflows/deploy.yml
Esta PR prueba el CD para publicar el frontend web a github pages!
- \[ ] Asegurate que la PR pase todos los chequeos de CI.
Database: PRs que modifican lógica …
=> feat: Deploy frontend workflow (#32)

.github/workflows/deploy.yml
Añadi los permisos y actualize la version de checkout
Database: PRs que modifican lógica relacionada a la …
=> fix: permmisions were added to deploy workflow

.github/workflows/deploy.yml
PR para probar que el CD funciona...
=> chore: Test CD integration

.github/workflows/deploy.yml
Arreglos para la workflow de deploy …
=> fix: steps were fixed on deploy workflow

.github/workflows/deploy.yml, sanitas_frontend/vite.config.js
Arreglo al vite configt y añadi el path en el yarn build
Database: PRs que modifican lógica relacionada a …
=> fix: vite config and deployment

wiki/Notas de Reuniones/Reunion23Abril.md, wiki/README.md
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/jira/software/projects/SCRUM/boards/1?assignee=712020%3Acdcb4e00-b0e8-48b4-8975-ba1f8c45edab&selectedIssue=SCRUM-30)
Añadi la mitad de la informacion de confluence en github
Database: PRs que modifican lógica relacionada a …
=> feat: confluece data was transcripted to github wiki

wiki/mantenimiento/db/README.md
Rediseñar la base de datos en base a nuevos requerimientos y convenios.
CI/CD: PRs …
=> fix: redesigned the ER database diagram

wiki/mantenimiento/Metodologia_de_desarrollo.md
Se añadió el nombre a la wiki. 
=> feat: added name to wiki

database/inserts.sql
Se arreglaron unos errores en los inserts. …
=> fix: fixed error with foreign key in inserts.sql

flake.nix
Esta PR arregla el tener que usar sudo dentro del entorno de nix develop para borrar archivos/carpetas. …
=> fix: Removed phantom alias

flake.nix, sanitas_frontend/package.json
Esta PR añade el storybook como un servicio más dentro de la interfaz de proces-compose que te genera `nix run .#restartServices`
Nix: PRs que …
=> feat: Added storybook service

sanitas_backend/package.json
Esta PR añade comandos para lintear y formatear el código del backend. No los he corrido porque de hacerlo generaría varios merge conflicts en las ramas de los endpoints de bianca y dubón.
Database: PRs que modifican lógica relacionada a la …
=> feat: Added linting and formatting commands

sanitas_frontend/src/dataLayer.mjs
Se eliminó el localhost para las funciones del dataLayer en addPatient. 
CI/CD: PRs …
=> fix: fixed localhost in API response 

sanitas_backend/README.md, sanitas_frontend/README.md, wiki/mantenimiento/frontend/README.md
Esta PR añade documentación para las convenciones a utilizar dentro del proyecto de Sanitas.
También mejora un poco la organización de la wiki …
=> feat: Added developing and conventions usage

.github/workflows/backend.yml, .github/workflows/deploy.yml, .github/workflows/frontend.yml
Esta PR añade continuos deployment al backend, lo que significa que ahora se publicaría solo!
Nix: PRs que modifican el entorno de desarrollo …
=> feat: backend CD on staging

database/inserts.sql
Se cambiaron algunos inserts que no estaban acorde a los campos necesitados.
CI/CD: PRs …
=> fix: changed database wrong types in paciente tables inserts

sanitas_frontend/src/dataLayer.mjs
Esta PR arregla el problema de que no se puede hacer local development cuando estamos corriendo el frontend de forma local.
Por favor revisen si el frontend ya les funciona junto con el backend si lo corren localmente estando en esta branch.
Frontend: PRs que modifican lógica relacionada al …
=> fix: Backend URL on development mode

flake.lock, sanitas_backend/package-lock.json, sanitas_backend/package.json, sanitas_backend/src/handlers/CreateFicha/create-ficha.integration.test.mjs, sanitas_backend/src/handlers/CreateFicha/create-ficha.mjs, sanitas_backend/template.yaml
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-86)
Se redefine el endpoint siguiento los lineamientos, cambios realizados incluyen el uso de minúsculas en vez de mayúsculas. Asimismo, se evita el uso de guiones.
=> fix: endpoint redifined add-patient

sanitas_frontend/src/components/Button/index.jsx, sanitas_frontend/src/components/DropdownMenu/index.jsx, sanitas_frontend/src/components/Input/index.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-105?atlOrigin=eyJpIjoiOTk5YmRlNDRiYWRkNDhlYWFlNTRjNjFlYzQwYTc0YjQiLCJwIjoiaiJ9)
Se crean componentes reutilizables para las páginas que ya tenemos del front end. 
Database: PRs que modifican lógica relacionada …
=> feat: added reusable components

flake.nix, sanitas_backend/template.yaml
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-120)
Esta PR añade el endpoint que permite obtener la información básica de un paciente. Será usado al momento de realizar la vista para actualizar un paciente.
Para hacer Code Review por favor verificar que todas las test corran además de que el endpoint pueda ser llamado desde el browser con ids válidas e inválidas.
Para hacer Q/A por favor revisar que el endpoint retorne todos los valores que se guarden en la tabla `Paciente`. …
=> feat: endpoint para obtener informacion general paciente

flake.nix, sanitas_backend/template.yaml
=> Revert "feat: endpoint para obtener informacion general paciente"

sanitas_backend/src/handlers/SearchPatient/search-patient.integration.test.mjs, sanitas_backend/src/handlers/SearchPatient/search-patient.mjs, sanitas_backend/template.yaml
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-87)
Esta PR refactoriza el endpoint del backend para buscar un paciente a las nuevas convenciones acordadas además de que añade la posibilidad de buscar por CUI
Database: PRs que modifican lógica relacionada a …
=> fix: scrum 87 refactorizar endpoint search patient

sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/views/AddPatientView/index.jsx, sanitas_frontend/src/views/SearchPatientView/index.jsx, sanitas_frontend/src/views/UpdateInfoView/index.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-126)
Se implementaron los componentes reutilizables en las vistas principales, AddPatientView, SearchPatientView y UpdateInfoView.
Wiki: PRs …
=> feat: implemented reusable components into views

.gitignore, conf.json, flake.nix, sanitas_backend/src/handlers/CreateFicha/create-ficha.integration.test.mjs, sanitas_backend/src/handlers/GetGeneralPatientInfo/get-general-patient-info.integration.test.mjs, sanitas_backend/src/handlers/testHelpers.mjs
Esta PR añade unos helpers para create un paciente de prueba, esto ayuda a que las tests sean más puras y no nos pase el que fallen simplemente porque se agregó otra test.
También esta PR añade JSDoc a la consola de desarrollo para generar documentación del código.
Frontend: PRs que modifican lógica …
=> fix: integration tests with helpers

sanitas_frontend/package.json, sanitas_frontend/src/components/Input/base.jsx, sanitas_frontend/src/components/Input/date.jsx, sanitas_frontend/src/components/Input/index.jsx, sanitas_frontend/src/components/Input/radio.jsx, sanitas_frontend/src/components/Input/search.jsx, sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/views/SearchPatientView/index.jsx, sanitas_frontend/src/views/SearchPatientView/index.test.jsx
Se implementó un nuevo tipo de input específico para búsqueda, se refactorizaron `exports`, se implementó programación defensiva y se corrigió el `dataLayer` en base a los nuevos cambios entrantes del endpoint de agregar paciente.
Database: …
=> fix: enhacement to search patient view with defensive programming

.github/workflows/backend.yml, .github/workflows/deploy.yml, .github/workflows/frontend.yml, flake.nix
Esta PR mejora la velocidad del CI/CD al quitar varias configuraciones extras en el nix file y hacer que la default shell sea la del nix develop.
Wiki: PRs que editan la …
=> fix: cicd speed by removing velocity

.github/workflows/backend.yml, .github/workflows/deploy.yml, .github/workflows/frontend.yml, flake.nix
* fix: region in deploy.yml
* fix: SAM build and deploy commands
* fix: improved CI/CD speed by removing pkgs …
=> fix: cicd speed by removing velocity (#105)

.github/workflows/deploy.yml
* fix: region in deploy.yml
* fix: SAM build and deploy commands
* fix: cicd speed by removing velocity (#105)
* fix: region in deploy.yml
* fix: SAM build and deploy commands
* fix: improved CI/CD speed by removing pkgs
* fix: deploy frontend error
Frontend: PRs que modifican lógica …
=> fix: GitHub actions error (#108)

.github/workflows/deploy.yml
=> fix: build env error and dist error fixed

sanitas_backend/package.json, sanitas_backend/src/handlers/UpdateCollaborator/update-collaborator.integration.test.mjs, sanitas_backend/src/handlers/UpdateCollaborator/update-collaborator.mjs, sanitas_backend/template.yaml
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-151?atlOrigin=eyJpIjoiMjNjNjFkOTJkZWRmNDhkZjgzNTAzZGFjMDY5ZGJjYWMiLCJwIjoiaiJ9)
=> feat: endpoint para actualizar datos colaborador

.github/workflows/backend.yml, .github/workflows/frontend.yml, sanitas_backend/samconfig.toml, sanitas_frontend/src/views/AddPatientView/index.test.jsx, sanitas_frontend/src/views/UpdateGeneralInformationView/index.jsx, sanitas_frontend/src/views/UpdateGeneralInformationView/index.test.jsx
Esta PR arregla las tests de los componentes que de vista que se tuvieron que refactorizar para añadir el sidebar. …
=> fix: frontend tests

sanitas_backend/src/handlers/GetGeneralStudentInfo/get-general-student-info-integration.test.mjs, sanitas_backend/src/handlers/GetGeneralStudentInfo/get-general-student-info.mjs, sanitas_backend/template.yaml
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/jira/software/projects/SCRUM/boards/1?selectedIssue=SCRUM-177)
Endpoint para obtener datos de estudiante
Nix: PRs que …
=> feat: get student info endpoint

sanitas_frontend/src/store.mjs, sanitas_frontend/src/utils/date.js, sanitas_frontend/src/utils/general.js, sanitas_frontend/src/utils/promiseWrapper.js, sanitas_frontend/src/views/SearchPatientView/index.jsx, sanitas_frontend/src/views/UpdateGeneralInformationView/index.jsx, sanitas_frontend/src/views/UpdateGeneralInformationView/index.stories.jsx, sanitas_frontend/src/views/UpdateGeneralInformationView/index.test.jsx
Esta PR refactoriza la vista para incluir suspense. …
=> refactor: update patient view

sanitas_frontend/src/theme.mjs
Se añadió un documento de theme para poder usar estilos generales entre las páginas.  …
=> feat: added a theme file to use in pages

sanitas_frontend/.storybook/preview-head.html, sanitas_frontend/src/components/Button/TextIcon/index.jsx, sanitas_frontend/src/components/Button/TextIcon/index.stories.jsx, sanitas_frontend/src/components/DashboardSidebar/index.jsx, sanitas_frontend/src/theme.mjs
Se añadieron estilos para la barra de navegación lateral. 
CI/CD: PRs relacionadas con …
=> feat: added styles to the sidebar

sanitas_frontend/src/components/Input/Base/base.jsx, sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/router.jsx, sanitas_frontend/src/views/UpdateGeneralInformationView/index.jsx, sanitas_frontend/src/views/UpdateGeneralInformationView/index.stories.jsx, sanitas_frontend/src/views/UpdateGeneralInformationView/index.test.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?selectedIssue=SCRUM-90)
Esta PR agrega todos los estilos y lógica necesaria para la sección de actualización de datos de estudiante de un paciente en Sanitas.
Database: PRs que …
=> feat: scrum 140 UI ux update student data

sanitas_backend/src/handlers/GetGeneralCollaboratorInfo/get-collaborator.integration.test.mjs, sanitas_backend/src/handlers/GetGeneralCollaboratorInfo/get-collaborator.mjs, sanitas_backend/template.yaml
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-175?atlOrigin=eyJpIjoiYWZlZWEyZWQ1NWQ3NGMyMThiMzNhYWI5MzZiYTFjNGEiLCJwIjoiaiJ9)
Endpoint para realizar el GET de los datos del colaborador
=> feat: endpoint get for collaborator

sanitas_backend/src/handlers/UpdatePatient/update-patient.integration.test.mjs, sanitas_backend/src/handlers/UpdatePatient/update-patient.mjs, sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/views/UpdateGeneralInformationView/index.jsx, sanitas_frontend/src/views/UpdateGeneralInformationView/index.stories.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/jira/software/projects/SCRUM/boards/1?assignee=712020%3Acdcb4e00-b0e8-48b4-8975-ba1f8c45edab&selectedIssue=SCRUM-171)
Añadi el UI/UX de la vista de update general de datos del paciente
Database: PRs que modifican lógica …
=> feat: general update UI ux

sanitas_backend/src/handlers/GetGeneralStudentInfo/get-general-student-info.mjs, sanitas_frontend/src/router.jsx, sanitas_frontend/src/views/UpdateGeneralInformationView/index.jsx
Esta PR arregla un bug en donde no se podía editar los campos de un paciente que no fuera estudiante debido a que el endpoint retornaba 404. …
=> feat: Added empty data return to studentinfo

sanitas_backend/layers/utils/utils/index.mjs, sanitas_backend/src/handlers/GetGeneralCollaboratorInfo/get-collaborator.integration.test.mjs, sanitas_backend/src/handlers/GetGeneralCollaboratorInfo/get-collaborator.mjs, sanitas_backend/src/handlers/UpdateCollaborator/update-collaborator.integration.test.mjs, sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/router.jsx, sanitas_frontend/src/views/UpdateGeneralInformationView/index.jsx, sanitas_frontend/src/views/UpdateGeneralInformationView/index.stories.jsx, sanitas_frontend/src/views/UpdateGeneralInformationView/index.test.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/jira/software/projects/SCRUM/boards/1?assignee=712020%3Acdcb4e00-b0e8-48b4-8975-ba1f8c45edab&selectedIssue=SCRUM-152)
Se añadio la seccion de modificar datos del colaborador
Database: PRs que modifican lógica relacionada a …
=> feat: colaborator view

sanitas_backend/src/handlers/UpdatePatient/update-patient.mjs
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-196)
Se corrigió una asignación de un valor al query que actualiza la información del paciente en el lambda de UpdatePatient. El problema era que se hacía una validación "patientData.es_mujer || null" pero como "patientData.es_mujer" es un boolean, entonces al ser falso se le asignaría null. Se cambió para que no le asignara null si es falso.
=> fix: fixed being unable to change patient sex

sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/views/AddPatientView/index.jsx, sanitas_frontend/src/views/AddPatientView/index.test.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-197?atlOrigin=eyJpIjoiNmFlNmM5Y2UyOWI4NDFkNWJmMzIwYmYyNTFiZWQ3ZjUiLCJwIjoiaiJ9)
=> fix: bug fixed, female option fixed

sanitas_backend/src/handlers/GetGeneralStudentInfo/get-general-student-info.mjs
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/jira/software/projects/SCRUM/boards/1?assignee=712020%3Acdcb4e00-b0e8-48b4-8975-ba1f8c45edab&selectedIssue=SCRUM-198)
Se corrigio un campo mal escrito sobre el carnet
Database: PRs que modifican lógica relacionada a la …
=> fix: carnet update bug on general tab

sanitas_frontend/src/views/UpdateGeneralInformationView/index.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-202)
Se añadió un padding de 2rem a un mensaje de error para alinearlo con el resto del contenido dentro de la vista.
- \[X\] Asignate a tí mismo dentro de la PR.
- \[X\] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[X\] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[X\] Agrega el link al issue de Jira.
- \[X\] Asegurate que la PR pase todos los chequeos de CI.
- \[X\] Ponle las tags correspondientes a tu PR.
Wiki: PRs que …
=> fix: Added padding to error message in UpdateGeneralInformationView

sanitas_frontend/src/components/DashboardSidebar/index.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-199)
Se reordenó los antecedentes del sidebar para que el orden sea igual al del documento de antecedentes.
- \[x\] Asignate a tí mismo dentro de la PR.
- \[x\] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[x\] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[x\] Agrega el link al issue de Jira.
- \[x\] Asegurate que la PR pase todos los chequeos de CI.
- \[x\] Ponle las tags correspondientes a tu PR.
Wiki: PRs que editan la …
=> fix: reordered dashboard icons

sanitas_backend/layers/utils/utils/defaultValues.mjs, sanitas_backend/layers/utils/utils/index.mjs, sanitas_backend/src/handlers/GetFamilyHistory/get-family-history-patient.integration.test.mjs, sanitas_backend/src/handlers/GetFamilyHistory/get-family-history-patient.mjs, sanitas_backend/src/handlers/GetTraumatologicalHistory/get-traumatological-history-patient.integration.test.mjs, sanitas_backend/src/handlers/GetTraumatologicalHistory/get-traumatological-history-patient.mjs, sanitas_backend/src/handlers/UpdateFamilyHistory/update-family-history-patient.integration.test.mjs, sanitas_backend/src/handlers/UpdateFamilyHistory/update-family-history-patient.mjs, sanitas_backend/src/handlers/UpdateTraumatologicalHistory/update-traumatological-history-patient.mjs, sanitas_backend/src/handlers/UpdateTraumatologicalHistory/update-traumatological-history.integration.test.mjs, sanitas_backend/src/handlers/testHelpers.mjs, sanitas_backend/template.yaml
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-203)
Se agregaron los endpoints de PUT y GET para la obtención y actualización/inserción para los antecedentes familiares y traumatológicos del paciente.
Database: PRs que modifican lógica relacionada a la …
=> feat: added familiar traumatological get put methods

.github/workflows/deploy.yml, flake.lock
=> feat: Added env variables to frontend deployment

sanitas_backend/layers/utils/utils/defaultValues.mjs, sanitas_backend/layers/utils/utils/index.mjs, sanitas_backend/src/handlers/GetPersonalHistory/get-personal-history-patient.integration.test.mjs, sanitas_backend/src/handlers/GetPersonalHistory/get-personal-history-patient.mjs, sanitas_backend/src/handlers/UpdatePersonalHistory/update-personal-history-patient.integration.test.mjs, sanitas_backend/src/handlers/UpdatePersonalHistory/update-personal-history-patient.mjs, sanitas_backend/src/handlers/testHelpers.mjs, sanitas_backend/template.yaml
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-214)
Esta Task crea los endpoints para actualizar y obtener la información correspondiente a los antecedentes Personales.
Acá puedes ver una ss de las integration tests corriendo satisfactoriamente:
Database: …
=> feat: scrum 95 personal medical history endpoints

wiki/mantenimiento/db/README.md
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-211)
Esta PR añade documentación para algunos endpoints de antecedentes médicos y qué significa el que retorne version 1.
Wiki: PRs que editan …
=> feat: Added documentation for medical history versioning

sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/views/AddPatientView/index.jsx, sanitas_frontend/src/views/AddPatientView/index.test.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/jira/software/projects/SCRUM/boards/1?assignee=712020%3Acdcb4e00-b0e8-48b4-8975-ba1f8c45edab&selectedIssue=SCRUM-200)
Añadi una pantalla de carga al add patiend
Database: PRs que modifican lógica relacionada a la base de …
=> feat: loading state on addpatient added

sanitas_backend/src/handlers/SearchPatient/search-patient.mjs, sanitas_backend/template.yaml, sanitas_frontend/src/components/DropdownMenu/index.jsx, sanitas_frontend/src/components/InformationCard/index.jsx, sanitas_frontend/src/components/PatientCard/index.jsx, sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/router.jsx, sanitas_frontend/src/views/History/Familiar/index.jsx, sanitas_frontend/src/views/History/Familiar/index.stories.jsx, sanitas_frontend/src/views/History/Surgical/index.jsx, sanitas_frontend/src/views/SearchPatientView/index.jsx, sanitas_frontend/src/views/UpdateTraumatologicalHistoryView/index.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-94?atlOrigin=eyJpIjoiNGFmNmU0MmY5YmY3NDI2ZWJmMjIzZmRlOTZlYjRmMjAiLCJwIjoiaiJ9)
Se añadió estilos y funcionalidad al antecedente de familiares. 
Database: PRs que modifican lógica relacionada a la base de …
=> feat: added gui to familiar history

sanitas_backend/layers/utils/utils/defaultValues.mjs, sanitas_backend/layers/utils/utils/index.mjs, sanitas_backend/src/handlers/GetNonPatologicalHistory/get-nonpatological-history-patient.integration.test.mjs, sanitas_backend/src/handlers/GetNonPatologicalHistory/get-nonpatological-history-patient.mjs, sanitas_backend/src/handlers/UpdateNonPatologicalHistory/update-nonpatological-history-patient.integration.test.mjs, sanitas_backend/src/handlers/UpdateNonPatologicalHistory/update-nonpatological-history-patient.mjs, sanitas_backend/src/handlers/testHelpers.mjs, sanitas_backend/template.yaml
Creación de los endpoints de PUT y GET para obtener los antecedentes no patológicos de un paciente. …
=> feat: nonpatological history endpoints

sanitas_frontend/src/components/InformationCard/index.jsx, sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/router.jsx, sanitas_frontend/src/views/History/Familiar/index.jsx, sanitas_frontend/src/views/History/Personal/index.jsx, sanitas_frontend/src/views/History/Personal/index.stories.jsx, sanitas_frontend/src/views/History/Personal/index.test.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-95)
Se añadió la pantalla de historial de antecedentes personales.
- \[X\] Asignate a tí mismo dentro de la PR.
- \[X\] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[X\] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[X\] Agrega el link al issue de Jira.
- \[X\] Asegurate que la PR pase todos los chequeos de CI.
- \[X\] Ponle las tags correspondientes a tu PR. …
=> feat: added GUI to personal history

sanitas_backend/layers/utils/utils/defaultValues.mjs, sanitas_backend/layers/utils/utils/index.mjs, sanitas_backend/src/handlers/GetNonPatologicalHistory/get-nonpatological-history-patient.integration.test.mjs, sanitas_backend/src/handlers/GetNonPatologicalHistory/get-nonpatological-history-patient.mjs, sanitas_backend/src/handlers/UpdateNonPatologicalHistory/update-nonpatological-history-patient.integration.test.mjs, sanitas_backend/src/handlers/UpdateNonPatologicalHistory/update-nonpatological-history-patient.mjs, sanitas_backend/src/handlers/testHelpers.mjs, sanitas_backend/template.yaml, sanitas_frontend/src/components/InformationCard/index.jsx, sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/router.jsx, sanitas_frontend/src/views/History/Familiar/index.jsx, sanitas_frontend/src/views/History/Personal/index.jsx, sanitas_frontend/src/views/History/Personal/index.stories.jsx, sanitas_frontend/src/views/History/Personal/index.test.jsx
Esta PR añade los cambios completos del sprint 8. …
=> feat: Sprint 8 results

.github/workflows/backend.yml, .github/workflows/frontend.yml, flake.lock, flake.nix, pg_hba.conf
Esta PR añade las integration tests dentro del CI/CD. Por el momento estamos usando mi fork de `devenv` pero cuando aprueben la PR se debe pasar a usar la dependencia de forma normal.
Database: PRs que modifican lógica relacionada a la base …
=> feat: backend integration tests

flake.nix
=> feat: Removed tui from process-compose

flake.nix
=> fix: integration tests on ci

sanitas_backend/template.yaml, sanitas_frontend/src/router.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-233?atlOrigin=eyJpIjoiMWMxNTE1M2MzNTk0NGYyNThlYjYyNGQ0YmY5ZjZiMjYiLCJwIjoiaiJ9)
Todos los formularios que se llenan hasta ahora en la aplicación requieren que un usuario esté autenticado para actualizar los datos, para ello se utilizará el componente RequireAuth
=> feat: Added authorization to forms and views

sanitas_backend/template.yaml, sanitas_frontend/src/dataLayer.mjs
Esta PR arregla las funciones del datalayer junto con algunas definiciones de endpoints en el template.yaml para que funcionen cuando hagamos deploy.
Wiki: PRs que editan la …
=> fix: datalayer functions

wiki/mantenimiento/db/README.md
=> fix: API Documentation

sanitas_backend/src/handlers/UpdateAllergicHistory/update-allergic-history-patient.integration.test.mjs, sanitas_backend/src/handlers/UpdateAllergicHistory/update-allergic-history-patient.mjs, sanitas_backend/src/handlers/UpdateFamilyHistory/update-family-history-patient.integration.test.mjs, sanitas_backend/src/handlers/UpdateFamilyHistory/update-family-history-patient.mjs, sanitas_backend/src/handlers/UpdateGynecoObstetricHistory/update-gynecoobstetric-history-patient.integration.test.mjs, sanitas_backend/src/handlers/UpdateGynecoObstetricHistory/update-gynecoobstetric-history-patient.mjs, sanitas_backend/src/handlers/UpdateNonPatologicalHistory/update-nonpatological-history-patient.integration.test.mjs, sanitas_backend/src/handlers/UpdateNonPatologicalHistory/update-nonpatological-history-patient.mjs, sanitas_backend/src/handlers/UpdatePatient/update-patient.integration.test.mjs, sanitas_backend/src/handlers/UpdatePatient/update-patient.mjs, sanitas_backend/src/handlers/UpdatePersonalHistory/update-personal-history-patient.integration.test.mjs, sanitas_backend/src/handlers/UpdatePersonalHistory/update-personal-history-patient.mjs, sanitas_backend/src/handlers/UpdatePsychiatricHistory/update-psychiatric-history-patient.integration.test.mjs, sanitas_backend/src/handlers/UpdatePsychiatricHistory/update-psychiatric-history-patient.mjs, sanitas_backend/src/handlers/UpdateSurgicalHistory/update-surgical-history-patient.integration.test.mjs, sanitas_backend/src/handlers/UpdateSurgicalHistory/update-surgical-history-patient.mjs, sanitas_backend/src/handlers/UpdateTraumatologicalHistory/update-traumatological-history-patient.mjs, sanitas_backend/src/handlers/UpdateTraumatologicalHistory/update-traumatological-history.integration.test.mjs, sanitas_backend/src/handlers/testHelpers.mjs
Esta PR añade la detección de roles para casi todos los endpoints de las doctoras, los únicos que faltan agregarle esta seguridad son los de datos generales. La principal razón por la que no se cumplen en esta PR es porque son parte de una tarea aparte.
Frontend: PRs que modifican lógica relacionada …
=> fix: role detection security

sanitas_frontend/src/views/History/Traumatological/index.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-246?atlOrigin=eyJpIjoiODk2YTY4OTZkYThjNGZhNjkyOTUzMmUwNTMxZTVhNTEiLCJwIjoiaiJ9)
=> feat: scrum 246 view traumatological update

sanitas_frontend/src/views/History/Surgical/index.jsx
Se añade método de actualización a la vista quirurgica.  …
=> fix: fixing update method in surgical view

sanitas_frontend/src/components/PatientCard/index.jsx, sanitas_frontend/src/views/History/Allergic/index.jsx, sanitas_frontend/src/views/History/NonPathological/index.jsx, sanitas_frontend/src/views/History/Surgical/index.jsx, sanitas_frontend/src/views/History/Traumatological/index.jsx
Arreglando el bug de cancelar de alérgicos y el de no patológicos. 
CI/CD: PRs …
=> fix: fixed cancel update

sanitas_frontend/src/components/InformationCard/index.jsx, sanitas_frontend/src/views/History/Familiar/index.jsx, sanitas_frontend/src/views/History/Traumatological/index.jsx
Se añadió el update a la vista de familiares. …
=> fix: update feature familiar view

sanitas_frontend/src/views/History/Personal/index.jsx, sanitas_frontend/src/views/History/Personal/index.test.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-243?atlOrigin=eyJpIjoiZGFlYjMyMzU0ZTdiNGM0YWI3YTEzYTcxN2IwNWIzOWIiLCJwIjoiaiJ9)
=> feat: update and cancel personal view

sanitas_frontend/src/views/History/Psichiatric/index.jsx, sanitas_frontend/src/views/History/Psichiatric/index.test.jsx
=> feat: git init base UI was made(only base UI working PRE BETA)

sanitas_frontend/src/views/History/Surgical/index.jsx, sanitas_frontend/src/views/History/Traumatological/index.jsx
Se arregló el bug de que apareciera 1989 para Juan, era un problema de zona horaria pero se puso método general para obtener el año, el cual fue: getUTCFullYear. Queda pendiente el de personal (Bianca lo colocará para no crear algún problema con lo que está haciendo)
Frontend: PRs que modifican …
=> fix: fixing bug in dropdown

sanitas_backend/src/handlers/UpdateStudentAllergicHistory/update-student-allergic-history-patient.integration.test.mjs, sanitas_backend/src/handlers/UpdateStudentAllergicHistory/update-student-allergic-history-patient.mjs, sanitas_backend/template.yaml, sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/router.jsx, sanitas_frontend/src/views/History/Students/StudentAllergic/index.jsx, sanitas_frontend/src/views/History/Students/StudentAllergic/index.stories.jsx, sanitas_frontend/src/views/History/Students/StudentAllergic/index.test.jsx
=> feat: student allergic view was added

sanitas_frontend/src/views/LoginView/index.jsx, sanitas_frontend/src/views/RegisterView/index.jsx
=> feat: login & register UI was fixed with error handlers and UI design

flake.nix, sanitas_backend/layers/db-conn/db-conn/index.mjs, sanitas_backend/src/handlers/GetAllergicHistory/get-allergic-history-patient.mjs, sanitas_backend/src/handlers/UpdateStudentAllergicHistory/update-student-allergic-history-patient.integration.test.mjs, sanitas_backend/src/handlers/UpdateStudentAllergicHistory/update-student-allergic-history-patient.mjs, sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/views/History/Students/StudentAllergic/index.jsx
=> fix: studend allergic view was fixed

flake.lock, flake.nix
Esta PR actualiza varias librerías base que utiliza el proyecto y simplifica el flake.nix
Nix: PRs que modifican el entorno de desarrollo en …
=> test: samcli and project dependencies update

sanitas_backend/layers/utils/utils/index.mjs, sanitas_backend/src/handlers/UpdateStudentAllergicHistory/update-student-allergic-history-patient.integration.test.mjs, sanitas_backend/src/handlers/UpdateStudentAllergicHistory/update-student-allergic-history-patient.mjs, sanitas_backend/src/handlers/UpdateStudentPersonalHistory/update-student-personal-history-patient.integration.test.mjs, sanitas_backend/src/handlers/UpdateStudentPersonalHistory/update-student-personal-history-patient.mjs, sanitas_backend/template.yaml, sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/router.jsx, sanitas_frontend/src/views/History/Personal/index.jsx, sanitas_frontend/src/views/History/Students/StudentPersonal/index.jsx, sanitas_frontend/src/views/History/Students/StudentPersonal/index.stories.jsx, sanitas_frontend/src/views/History/Students/StudentPersonal/index.test.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-267?atlOrigin=eyJpIjoiMDE3MzBkNDk0Mzk4NDhkN2FlYjc3MjZjNDFiZjhkOWMiLCJwIjoiaiJ9) …
=> feat: view from student personal added

sanitas_frontend/src/router.jsx, sanitas_frontend/src/views/SearchPatientView/index.jsx, sanitas_frontend/src/views/SearchPatientView/index.test.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-262?atlOrigin=eyJpIjoiZWY4OGY0OWViZmNlNGJhZThhZGNiYmNkNGZjZTkxMDMiLCJwIjoiaiJ9) …
=> feat: search role navigation

sanitas_frontend/src/views/History/Students/StudentSurgical/index.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-231) …
=> fix: removed update button from studentsurgical

sanitas_backend/src/handlers/UpdateStudentFamiliarHistory/update-student-familiar-history-patient.integration.test.mjs, sanitas_backend/src/handlers/UpdateStudentFamiliarHistory/update-student-familiar-history-patient.mjs, sanitas_backend/template.yaml
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-272?atlOrigin=eyJpIjoiMWM2NmRkODMyZmQ4NGY3N2IzZTFmNjQ4NzAyMGVhYjciLCJwIjoiaiJ9) …
=> feat: endpoint for familiar student view

.gitignore, README.md, flake.nix, sanitas_backend/layers/utils/utils/index.mjs, sanitas_backend/package.json, sanitas_backend/src/handlers/UpdateStudentGynecoObstetricHistory/update-student-gyneco-obstetric-history.integration.test.mjs, sanitas_backend/src/handlers/UpdateStudentGynecoObstetricHistory/update-student-gyneco-obstetric-history.mjs, sanitas_backend/template.yaml, sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/router.jsx, sanitas_frontend/src/views/History/Students/StudentObGyn/index.jsx, sanitas_frontend/src/views/History/Students/StudentObGyn/index.stories.jsx, sanitas_frontend/src/views/History/Students/StudentObGyn/index.test.jsx, sanitas_frontend/src/views/History/Students/StudentPersonal/index.stories.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-273)
Esta PR añade soporte para que un estudiante pueda modificar sus datos ginecoobstétricos.
Nix: PRs que …
=> feat: scrum 273 gineco student view

sanitas_frontend/src/components/StudentDashboardTopBar/index.jsx, sanitas_frontend/src/components/StudentDashboardTopBar/index.stories.jsx, sanitas_frontend/src/router.jsx, sanitas_frontend/src/views/History/Students/StudentAllergic/index.jsx, sanitas_frontend/src/views/History/Students/StudentAllergic/index.stories.jsx, sanitas_frontend/src/views/History/Students/StudentAllergic/index.test.jsx, sanitas_frontend/src/views/History/Students/StudentNonPathological/index.jsx, sanitas_frontend/src/views/History/Students/StudentNonPathological/index.stories.jsx, sanitas_frontend/src/views/History/Students/StudentNonPathological/index.test.jsx, sanitas_frontend/src/views/History/Students/StudentPersonal/index.jsx, sanitas_frontend/src/views/History/Students/StudentPersonal/index.stories.jsx, sanitas_frontend/src/views/History/Students/StudentPersonal/index.test.jsx, sanitas_frontend/src/views/History/Students/StudentPsichiatric/index.jsx, sanitas_frontend/src/views/History/Students/StudentPsichiatric/index.stories.jsx, sanitas_frontend/src/views/History/Students/StudentPsichiatric/index.test.jsx, sanitas_frontend/src/views/History/Students/StudentSurgical/index.jsx, sanitas_frontend/src/views/History/Students/StudentSurgical/index.stories.jsx, sanitas_frontend/src/views/History/Students/StudentSurgical/index.test.jsx, sanitas_frontend/src/views/UpdatePatientGeneralInformationView/index.jsx, sanitas_frontend/src/views/UpdatePatientGeneralInformationView/index.stories.jsx, sanitas_frontend/src/views/UpdatePatientGeneralInformationView/index.test.jsx
Añadiendo navegación a la vista de estudiante.  …
=> feat: adding top bar to students view

sanitas_frontend/src/store.mjs, sanitas_frontend/src/views/SearchPatientView/index.test.jsx
Esta PR cambia el tipo de búsqueda por defecto a nombres y apellidos para que sea más fácil la búsqueda de estudiantes.
Nix: PRs que modifican …
=> fix: Changed default search term

sanitas_frontend/src/cognito.mjs, sanitas_frontend/src/components/DashboardSidebar/index.jsx, sanitas_frontend/src/components/DashboardSidebar/index.stories.jsx, sanitas_frontend/src/components/RequireAuth/index.jsx, sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/router.jsx, sanitas_frontend/src/store.mjs, sanitas_frontend/src/views/History/Allergic/index.stories.jsx, sanitas_frontend/src/views/History/Familiar/index.stories.jsx, sanitas_frontend/src/views/History/NonPathological/index.stories.jsx, sanitas_frontend/src/views/History/ObGyn/index.stories.jsx, sanitas_frontend/src/views/History/Personal/index.stories.jsx, sanitas_frontend/src/views/History/Psichiatric/index.stories.jsx, sanitas_frontend/src/views/History/Surgical/index.stories.jsx, sanitas_frontend/src/views/History/Traumatological/index.stories.jsx, sanitas_frontend/src/views/LoginView/index.stories.jsx
Esta PR arregla el display del usuario actual dentro del sidebar de la vista de las doctoras, para que ya no salga más el "Pedrito Perez".
Nix: …
=> feat: Added email extraction

sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/router.jsx, sanitas_frontend/src/views/History/Students/StudentObGyn/index.jsx, sanitas_frontend/src/views/History/Students/StudentObGyn/index.stories.jsx, sanitas_frontend/src/views/History/Students/StudentObGyn/index.test.jsx
Añade la vista de Ginecoobstétricos al sidebar de paciente. Además cambia la vista por defecto a la de datos generales, para que ya no salga el "WIP: Formulario de paciente".
Database: PRs que modifican lógica relacionada a la base de …
=> fix: routing to obgyn and form index

sanitas_backend/layers/utils/utils/index.mjs, sanitas_backend/src/handlers/UpdateStudentTraumatologicalHistory/update-student-traumatological-history-patient.mjs, sanitas_backend/src/handlers/UpdateStudentTraumatologicalHistory/update-student-traumatological-history.integration.test.mjs, sanitas_backend/template.yaml, sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/router.jsx, sanitas_frontend/src/views/History/Students/StudentTraumatological/index.jsx, sanitas_frontend/src/views/History/Students/StudentTraumatological/index.stories.jsx, sanitas_frontend/src/views/History/Students/StudentTraumatological/index.test.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-250)
Implementación de la vista para el formulario de paciente para antecedentes traumatológicos.
- \[x\] Asignate a tí mismo dentro de la PR.
- \[x\] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[x\] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[x\] Agrega el link al issue de Jira.
- \[x\] Asegurate que la PR pase todos los chequeos de CI.
- \[x\] Ponle las tags correspondientes a tu PR.
Nix: PRs …
=> feat: student traumatological view

sanitas_frontend/src/components/StudentDashboardTopBar/index.jsx
Se añade JSDoc al Top Bar de estudiante.
=> feat: adding JSDoc

sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/router.jsx, sanitas_frontend/src/views/History/Students/StudentFamiliar/index.jsx, sanitas_frontend/src/views/History/Students/StudentFamiliar/index.stories.jsx, sanitas_frontend/src/views/History/Students/StudentFamiliar/index.test.jsx
=> feat: student view added

sanitas_frontend/src/views/RegisterView/index.jsx
Se agrego un modal para darle a conocer al usuario que se ha enviado un correo para confirmar su cuenta luego de registrarse en la plataforma. …
=> feat: added email verification modal to Register View

sanitas_backend/src/handlers/GetGeneralCollaboratorInfo/get-collaborator.integration.test.mjs, sanitas_backend/src/handlers/GetGeneralCollaboratorInfo/get-collaborator.mjs, sanitas_backend/src/handlers/GetGeneralStudentInfo/get-general-student-info.mjs, sanitas_backend/src/handlers/UpdateStudentGeneralInformation/update-student-general-information.integration.test.mjs, sanitas_backend/src/handlers/UpdateStudentGeneralInformation/update-student-general-information.mjs, sanitas_frontend/src/utils/refreshHook.js, sanitas_frontend/src/views/AddPatientView/index.jsx, sanitas_frontend/src/views/UpdatePatientGeneralInformationView/index.jsx
Esta PR arregla el bug del sexo del paciente. …
=> fix: update sex in patient general info

sanitas_frontend/src/components/DashboardSidebar/index.jsx, sanitas_frontend/src/components/StudentDashboardTopBar/index.jsx, sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/router.jsx, sanitas_frontend/src/views/History/Students/StudentAllergic/index.test.jsx, sanitas_frontend/src/views/History/Students/StudentFamiliar/index.test.jsx, sanitas_frontend/src/views/History/Students/StudentNonPathological/index.test.jsx, sanitas_frontend/src/views/History/Students/StudentPersonal/index.test.jsx, sanitas_frontend/src/views/History/Students/StudentPsichiatric/index.test.jsx, sanitas_frontend/src/views/History/Students/StudentSurgical/index.test.jsx, sanitas_frontend/src/views/History/Students/StudentTraumatological/index.test.jsx, sanitas_frontend/src/views/UpdateGeneralInformationView/index.jsx, sanitas_frontend/src/views/UpdatePatientGeneralInformationView/index.jsx, sanitas_frontend/src/views/UpdatePatientGeneralInformationView/index.test.jsx
=> feat: ginecob sex handler for side bars

sanitas_backend/template.yaml, sanitas_frontend/src/router.jsx, sanitas_frontend/src/views/History/ObGyn/index.jsx, wiki/mantenimiento/db/README.md
=> feat: wiki updates, and small fixes

sanitas_backend/template.yaml, sanitas_frontend/src/router.jsx, sanitas_frontend/src/views/History/ObGyn/index.jsx, wiki/mantenimiento/db/README.md
=> fix: deploy errors 2

sanitas_frontend/src/components/StudentDashboardTopBar/index.jsx, sanitas_frontend/src/components/StudentDashboardTopBar/index.stories.jsx, sanitas_frontend/src/router.jsx, sanitas_frontend/src/views/History/Students/StudentObGyn/index.jsx, sanitas_frontend/src/views/History/Students/StudentTraumatological/index.jsx
=> fix: deploy 4

sanitas_backend/src/handlers/GetLinkedPatient/get-linked-patient.integration.test.mjs, sanitas_backend/src/handlers/GetLinkedPatient/get-linked-patient.mjs, sanitas_frontend/src/components/StudentDashboardTopBar/index.jsx, sanitas_frontend/src/components/StudentDashboardTopBar/index.stories.jsx, sanitas_frontend/src/router.jsx, sanitas_frontend/src/views/History/Students/StudentObGyn/index.jsx, sanitas_frontend/src/views/History/Students/StudentTraumatological/index.jsx
=> fix: deploy 5

sanitas_backend/src/handlers/testHelpers.mjs, sanitas_frontend/src/components/StudentDashboardTopBar/index.jsx, sanitas_frontend/src/views/History/Students/StudentTraumatological/index.jsx, sanitas_frontend/src/views/UpdatePatientGeneralInformationView/index.stories.jsx
Esta PR añade soporte para móbil para el componente del navbar de los estudiantes. …
=> feat: Added responsive traits to component

sanitas_frontend/src/views/History/Students/StudentPsichiatric/index.jsx, sanitas_frontend/src/views/History/Students/StudentPsichiatric/index.stories.jsx
Se añadió vista de mobile para la vista de psiquiátricos de estudiantes. 
CI/CD: PRs …
=> feat: adding responsive psycho student view

sanitas_frontend/src/views/History/Students/StudentNonPathological/index.jsx, sanitas_frontend/src/views/History/Students/StudentNonPathological/index.stories.jsx
Se añade vista para mobile para la vista de no patológicos de estudiante. 
CI/CD: PRs …
=> feat: Adding responsive mobile non pathologic

sanitas_frontend/src/utils/measureScaling.js, sanitas_frontend/src/views/History/Students/StudentSurgical/index.jsx, sanitas_frontend/src/views/History/Students/StudentSurgical/index.stories.jsx, sanitas_frontend/src/views/History/Students/StudentTraumatological/index.jsx, sanitas_frontend/src/views/History/Students/StudentTraumatological/index.stories.jsx
Responsive para vistas de Quirúrigicos/Traumatológicos. …
=> feat: mobile version for surgical traumatologic

sanitas_frontend/src/views/History/Students/StudentAllergic/index.jsx, sanitas_frontend/src/views/History/Students/StudentAllergic/index.stories.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-281)
Esta PR añade la vista móvil para la vista de antecedentes alérgicos. …
=> feat: mobile view alergic

sanitas_frontend/src/views/LoginView/index.jsx, sanitas_frontend/src/views/RegisterView/index.jsx
=> feat: responsive for login and register view

sanitas_backend/layers/db-conn/db-conn/index.mjs, sanitas_backend/src/handlers/GetAllergicHistory/get-allergic-history-patient.integration.test.mjs, sanitas_backend/src/handlers/GetAllergicHistory/get-allergic-history-patient.mjs, sanitas_backend/src/handlers/GetFamilyHistory/get-family-history-patient.integration.test.mjs, sanitas_backend/src/handlers/GetFamilyHistory/get-family-history-patient.mjs, sanitas_backend/src/handlers/GetGeneralCollaboratorInfo/get-collaborator.integration.test.mjs, sanitas_backend/src/handlers/GetGeneralCollaboratorInfo/get-collaborator.mjs, sanitas_backend/src/handlers/GetGeneralPatientInfo/get-general-patient-info.integration.test.mjs, sanitas_backend/src/handlers/GetGeneralPatientInfo/get-general-patient-info.mjs, sanitas_backend/src/handlers/GetGeneralStudentInfo/get-general-student-info-integration.test.mjs, sanitas_backend/src/handlers/GetGeneralStudentInfo/get-general-student-info.mjs, sanitas_backend/src/handlers/GetGynecoObstetricHistory/get-gynecoobstetric-history-patient.integration.test.mjs, sanitas_backend/src/handlers/GetGynecoObstetricHistory/get-gynecoobstetric-history-patient.mjs, sanitas_backend/src/handlers/GetLinkedPatient/get-linked-patient.integration.test.mjs, sanitas_backend/src/handlers/GetNonPatologicalHistory/index.integration.test.mjs, sanitas_backend/src/handlers/GetNonPatologicalHistory/index.mjs, sanitas_backend/src/handlers/GetPersonalHistory/get-personal-history-patient.integration.test.mjs, sanitas_backend/src/handlers/GetPersonalHistory/get-personal-history-patient.mjs, sanitas_backend/src/handlers/GetPsychiatricHistory/get-psychiatric-history-patient.integration.test.mjs, sanitas_backend/src/handlers/GetPsychiatricHistory/get-psychiatric-history-patient.mjs, sanitas_backend/src/handlers/GetSurgicalHistory/get-surgical-history-patient.integration.test.mjs, sanitas_backend/src/handlers/GetSurgicalHistory/get-surgical-history-patient.mjs, sanitas_backend/src/handlers/GetTraumatologicalHistory/get-traumatological-history-patient.integration.test.mjs, sanitas_backend/src/handlers/GetTraumatologicalHistory/get-traumatological-history-patient.mjs, sanitas_backend/src/handlers/LinkAccountToPatient/link-account-to-patient.integration.test.mjs
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-275)
Esta PR añade protección a los endpoints GET para que solo personas autorizadas puedan acceder a los datos.
Wiki: PRs que editan la …
=> feat: get endpoint protection

sanitas_frontend/src/components/Button/Base/index.jsx, sanitas_frontend/src/components/Button/Icon/index.jsx, sanitas_frontend/src/components/Button/TextIcon/index.jsx, sanitas_frontend/src/components/StudentDashboardTopBar/index.jsx, sanitas_frontend/src/views/History/Students/StudentObGyn/index.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-281)
Esta PR añade soporte para móvil a la vista de ginecoobstétricos para pacientes. …
=> feat: gynob mobile view

sanitas_frontend/src/views/History/Students/StudentNonPathological/index.jsx, sanitas_frontend/src/views/History/Students/StudentPsichiatric/index.jsx
Cambiando de useEffect a useWindowsSize
=> fix: using use windows size in psycho and non pathologic

sanitas_frontend/src/views/History/Students/StudentFamiliar/index.jsx, sanitas_frontend/src/views/History/Students/StudentFamiliar/index.stories.jsx
=> feat: familiar responsive view

sanitas_backend/src/handlers/CheckCui/check-cui.mjs, sanitas_backend/src/handlers/CreatePatient/create-patient.mjs, sanitas_backend/src/handlers/GetAllergicHistory/get-allergic-history-patient.mjs, sanitas_backend/src/handlers/GetFamilyHistory/get-family-history-patient.mjs, sanitas_backend/src/handlers/GetGeneralCollaboratorInfo/get-collaborator.mjs, sanitas_backend/src/handlers/GetGeneralPatientInfo/get-general-patient-info.mjs, sanitas_backend/src/handlers/GetGeneralStudentInfo/get-general-student-info.mjs, sanitas_backend/src/handlers/GetGynecoObstetricHistory/get-gynecoobstetric-history-patient.mjs, sanitas_backend/src/handlers/GetNonPatologicalHistory/index.mjs, sanitas_backend/src/handlers/GetPersonalHistory/get-personal-history-patient.mjs, sanitas_backend/src/handlers/GetPsychiatricHistory/get-psychiatric-history-patient.mjs, sanitas_backend/src/handlers/GetSurgicalHistory/get-surgical-history-patient.mjs, sanitas_backend/src/handlers/GetTraumatologicalHistory/get-traumatological-history-patient.mjs, sanitas_backend/src/handlers/HealthCheck/health-check.mjs, sanitas_backend/src/handlers/SearchPatient/search-patient.mjs
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-276)
Esta PR modifica los endpoints restantes para que utilicen transaction y createResponse
Nix: PRs que …
=> fix: CheckCUI and CreatePatient

sanitas_frontend/src/views/LoginView/index.jsx
=> Fix login bug attempt 2

sanitas_frontend/src/views/LoginView/index.jsx
* fix: double click fix attempt 1
* fix: bug fix attempt 2
CI/CD: PRs …
=> Fix login bug attempt 2 (#262)

sanitas_frontend/src/views/LoginView/index.jsx
=> fix: login migration toast

sanitas_frontend/src/views/LoginView/index.jsx
=> fix: try #3

sanitas_frontend/src/views/LoginView/index.jsx
=> fix: format error on login and console logs

sanitas_frontend/src/views/LoginView/index.jsx
=> fix: Removed double component on login

sanitas_frontend/src/views/LoginView/index.jsx
=> fix: number #4

sanitas_frontend/src/views/History/Allergic/index.jsx, sanitas_frontend/src/views/History/NonPathological/index.jsx, sanitas_frontend/src/views/History/ObGyn/index.jsx, sanitas_frontend/src/views/History/Personal/index.jsx, sanitas_frontend/src/views/History/Personal/index.test.jsx, sanitas_frontend/src/views/History/Psichiatric/index.jsx
=> fix: toast implementation fixed

sanitas_frontend/src/components/Button/Base/index.jsx, sanitas_frontend/src/components/DashboardSidebar/index.jsx, sanitas_frontend/src/components/DropdownMenu/index.jsx, sanitas_frontend/src/components/Input/Search/search.jsx, sanitas_frontend/src/components/PatientCard/index.jsx, sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/views/AddPatientView/index.jsx, sanitas_frontend/src/views/AddPatientView/index.test.jsx, sanitas_frontend/src/views/History/Allergic/index.jsx, sanitas_frontend/src/views/History/Familiar/index.jsx, sanitas_frontend/src/views/History/ObGyn/index.jsx, sanitas_frontend/src/views/History/Personal/index.jsx, sanitas_frontend/src/views/SearchPatientView/index.jsx
Se arreglan esitlos generales de la vista de doctor.  …
=> fix: fixing doctor view styles

sanitas_frontend/src/components/RequireAuth/index.jsx
=> feat: username not found bug fix

sanitas_frontend/src/cognito.mjs, sanitas_frontend/src/components/Button/Base/index.jsx, sanitas_frontend/src/components/DashboardSidebar/index.jsx, sanitas_frontend/src/components/DropdownMenu/index.jsx, sanitas_frontend/src/components/Input/Search/search.jsx, sanitas_frontend/src/components/PatientCard/index.jsx, sanitas_frontend/src/components/RequireAuth/index.jsx, sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/views/AddPatientView/index.jsx, sanitas_frontend/src/views/AddPatientView/index.test.jsx, sanitas_frontend/src/views/History/Allergic/index.jsx, sanitas_frontend/src/views/History/Familiar/index.jsx, sanitas_frontend/src/views/History/NonPathological/index.jsx, sanitas_frontend/src/views/History/ObGyn/index.jsx, sanitas_frontend/src/views/History/Personal/index.jsx, sanitas_frontend/src/views/History/Personal/index.test.jsx, sanitas_frontend/src/views/History/Psichiatric/index.jsx, sanitas_frontend/src/views/LoginView/index.jsx, sanitas_frontend/src/views/SearchPatientView/index.jsx
=> fix: try #6 or idk

sanitas_frontend/src/components/RequireAuth/index.jsx
=> fix: logs v2

sanitas_frontend/src/components/RequireAuth/index.jsx
=> fix: #7 idk

sanitas_frontend/src/components/RequireAuth/index.jsx
=> fix: username not found v3

sanitas_frontend/src/components/RequireAuth/index.jsx
=> fix: console logs removal

sanitas_frontend/src/views/CreatePatientView/index.jsx, sanitas_frontend/src/views/History/Students/StudentAllergic/index.jsx, sanitas_frontend/src/views/History/Students/StudentFamiliar/index.jsx, sanitas_frontend/src/views/History/Students/StudentObGyn/index.jsx, sanitas_frontend/src/views/History/Students/StudentPersonal/index.jsx, sanitas_frontend/src/views/History/Students/StudentSurgical/index.jsx, sanitas_frontend/src/views/History/Students/StudentTraumatological/index.jsx, sanitas_frontend/src/views/LinkPatientView/index.jsx, sanitas_frontend/src/views/StudentWelcomeView/index.jsx
Se corrigen estilos para ls vista móvil y de PC del paciente …
=> fix: fixing patient pc and mobile view

flake.nix, sanitas_backend/package.json, sanitas_backend/perfTests/helpers.js, sanitas_backend/perfTests/loadTesting/doctor-searching-patients.js, sanitas_backend/perfTests/loadTesting/patient-filling-form.js, sanitas_backend/perfTests/loadTesting/patient-reading-data.js
Esta PR añader tests de carga al repositorio …
=> feat: add balance tests

sanitas_frontend/README.md, sanitas_frontend/src/views/RegisterView/index.jsx
Esta PR actualiza la funcionalidad de la vista de Register para que funcione en móbil. Además actualiza la wiki de frontend.
Nix: PRs que …
=> fix: register view not working on mobile

sanitas_frontend/src/views/LinkPatientView/index.jsx
=> feat: responsive view for link patient

sanitas_frontend/src/views/CreatePatientView/index.jsx
=> feat: responsive view por create patient

sanitas_frontend/src/views/StudentWelcomeView/index.jsx
=> feat: responsive view for welcome view

sanitas_frontend/src/views/UpdatePatientGeneralInformationView/index.jsx
=> feat: responsive view for General Data

sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/views/CreatePatientView/index.jsx
=> fix: fixes in create patient view

sanitas_backend/src/handlers/UpdateStudentCollaboratorInformation/update-student-collaborator-information.mjs, sanitas_backend/src/handlers/UpdateStudentGeneralInformation/update-student-general-information.integration.test.mjs, sanitas_backend/src/handlers/UpdateStudentGeneralInformation/update-student-general-information.mjs, sanitas_backend/src/handlers/UpdateStudentStudentInformation/update-student-student-information.mjs
El endpoint ahora permite modificar datos para estudiantes
CI/CD: PRs relacionadas con …
=> fix: Endpoint configuration to allow modifying values

sanitas_frontend/src/dataLayer.mjs, sanitas_frontend/src/views/History/Psichiatric/index.jsx, sanitas_frontend/src/views/History/Students/StudentNonPathological/index.jsx, sanitas_frontend/src/views/History/Students/StudentPsichiatric/index.jsx
El botón de `Cancelar Medicamento` seguía apareciendo para un medicamento nuevo ya enviado a la base de datos. …
=> fix: now button for cancel medication only appears when the medicament added is new

wiki/README.md, wiki/mantenimiento/Deploy.md
=> feat: Added deploy guide

sanitas_frontend/src/components/StudentDashboardTopBar/index.jsx, sanitas_frontend/src/views/UpdatePatientGeneralInformationView/index.jsx
[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-304)
Datos generales no debería de tener el botón de editar ya que los demás no lo tienen. 
Validación en endpoint pendiente aún.
- \[x\] Asignate a tí mismo dentro de la PR.
- \[x\] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[x\] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[x\] Agrega el link al issue de Jira.
- \[x\] Asegurate que la PR pase todos los chequeos de CI.
- \[x\] Ponle las tags correspondientes a tu PR.
Wiki: …
=> fix: removed edit button

database/tables.sql, sanitas_frontend/src/views/UpdateGeneralInformationView/index.jsx, sanitas_frontend/src/views/UpdatePatientGeneralInformationView/index.jsx
Se cambio la longitud máxima de Área y Carrera, para el apartado de doctoras y el apartado de estudiantes. …
=> fix: max length on general information view input

sanitas_frontend/src/views/Appointments/index.jsx, sanitas_frontend/src/views/CreatePatientView/index.jsx, sanitas_frontend/src/views/History/Allergic/index.jsx, sanitas_frontend/src/views/History/Familiar/index.jsx, sanitas_frontend/src/views/History/Personal/index.jsx, sanitas_frontend/src/views/History/Students/StudentFamiliar/index.jsx, sanitas_frontend/src/views/History/Students/StudentNonPathological/index.jsx, sanitas_frontend/src/views/History/Students/StudentPersonal/index.jsx, sanitas_frontend/src/views/History/Students/StudentSurgical/index.jsx, sanitas_frontend/src/views/History/Students/StudentTraumatological/index.jsx, sanitas_frontend/src/views/History/Surgical/index.jsx, sanitas_frontend/src/views/History/Traumatological/index.jsx, sanitas_frontend/src/views/SearchPatientView/index.jsx, sanitas_frontend/src/views/StudentWelcomeView/index.jsx, sanitas_frontend/src/views/UpdateGeneralInformationView/index.jsx, sanitas_frontend/src/views/UpdatePatientGeneralInformationView/index.jsx
Se realizaron cambios de visuales en placeholders, se añadió verificación de edad al crear el paciente, se añadieron memo hook para las vistas con suspense y se quitó la visualización de sangre en la vista de no patológico en estudiante.  …
=> fix: fixing non pathologic message and use memo hook in views

sanitas_frontend/src/views/UpdateGeneralInformationView/index.jsx, sanitas_frontend/src/views/UpdatePatientGeneralInformationView/index.jsx
=> fix: change Seguro to Seguro Médico

sanitas_frontend/src/utils/errorhandlerstoasts.js, sanitas_frontend/src/views/Appointments/index.jsx, sanitas_frontend/src/views/CreatePatientView/index.jsx, sanitas_frontend/src/views/History/Allergic/index.jsx, sanitas_frontend/src/views/History/Familiar/index.jsx, sanitas_frontend/src/views/History/NonPathological/index.jsx, sanitas_frontend/src/views/History/ObGyn/index.jsx, sanitas_frontend/src/views/History/Personal/index.jsx, sanitas_frontend/src/views/History/Psichiatric/index.jsx, sanitas_frontend/src/views/History/Students/StudentAllergic/index.jsx, sanitas_frontend/src/views/History/Students/StudentFamiliar/index.jsx, sanitas_frontend/src/views/History/Students/StudentNonPathological/index.jsx, sanitas_frontend/src/views/History/Students/StudentObGyn/index.jsx, sanitas_frontend/src/views/History/Students/StudentPersonal/index.jsx, sanitas_frontend/src/views/History/Students/StudentPsichiatric/index.jsx, sanitas_frontend/src/views/History/Students/StudentSurgical/index.jsx, sanitas_frontend/src/views/History/Students/StudentTraumatological/index.jsx, sanitas_frontend/src/views/History/Surgical/index.jsx, sanitas_frontend/src/views/History/Traumatological/index.jsx, sanitas_frontend/src/views/LinkPatientView/index.jsx
=> feat: error handlers for toasts
